# Common Makefile between Z1 and Z1SP

CONTIKI_TARGET_SOURCEFILES += contiki-z1-platform.c
CLEAN += *.z1-wais

include $(CONTIKI)/platform/z1-wais/Makefile.common

MODULES += core/net \
           core/net/mac core/net/mac/contikimac \
           core/net/llsec \
           dev/cc2420 dev/sht11
